/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.DbController;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author S_Ale AKA S0Ale
 */
public class AppWindow extends javax.swing.JFrame {
    private DbController controller;
    private CardLayout layout;
    private ItemList itemPanel;
    private LoginPanel login;
    private ViewPanel visualizer;
    
    /**
     * Creates new form AppWindow
     */
    public AppWindow() {
        initComponents();
        layout = new CardLayout();
        controller = new DbController();
        mainPanel.setLayout(layout);
        itemPanel = new ItemList(this);
        login = new LoginPanel(this);
        visualizer = new ViewPanel(this);
        mainPanel.add(login, "login");
        mainPanel.add(itemPanel, "items");
        mainPanel.add(visualizer, "view");
        initPanel();
    }
    
    public DbController getController(){
        return controller;
    }
    
    private void initPanel(){
        layout.show(mainPanel, "login");
    }
    
    public void showLoginPanel(){
        if(login == null) login = new LoginPanel(this); 
        layout.show(mainPanel, "login");
    }
    
    public void showItemsPanel(){
        if(itemPanel == null) itemPanel = new ItemList(this); 
        itemPanel.updateItemPanel();
        layout.show(mainPanel, "items");
    }
    
    public void showViewPanel(){
        if(visualizer == null) visualizer = new ViewPanel(this); 
        layout.show(mainPanel, "view");
    }
    
    public void updateViewPanel(String desc, String date, String state, String continent, String modelPath, String audioPath){
        visualizer.setViewPanel(desc, date, state, continent, modelPath, audioPath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        mainPanel = new javax.swing.JPanel();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(640, 360));
        setResizable(false);

        mainPanel.setName(""); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.install();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("com.formdev.flatlaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppWindow frame = new AppWindow();
                frame.setVisible(true);
                frame.addWindowListener(new WindowAdapter(){
                    @Override
                    public void windowClosing(WindowEvent e){
                         frame.closeAll();
                    }
                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    private int closeAll() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if(visualizer.getPlayer() != null && visualizer.getPlayer().isStarted())visualizer.getPlayer().stop();
        controller.logout();
        File dirMuseo = new File(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\museo");
        if(dirMuseo.exists()) {
            for(File file: dirMuseo.getAbsoluteFile().listFiles())
                if (!file.isDirectory())
                    file.delete();
        }
        System.exit(0);
        return 1;
    }
}
